import styled from "styled-components";

export const BigLogoStyles = styled.div`
  width: 200px;
  height: 200px;

  @media (min-width: 800px) {
    width: 400px;
    height: 400px;
  }

  /***************************************************
 * Generated by SVG Artista on 12/24/2021, 8:18:46 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

  @-webkit-keyframes animate-svg-stroke-1 {
    0% {
      stroke-dashoffset: 1951.7640380859375px;
      stroke-dasharray: 1951.7640380859375px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 1951.7640380859375px;
    }
  }

  @keyframes animate-svg-stroke-1 {
    0% {
      stroke-dashoffset: 1951.7640380859375px;
      stroke-dasharray: 1951.7640380859375px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 1951.7640380859375px;
    }
  }

  @-webkit-keyframes animate-svg-fill-1 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(47, 47, 47);
    }
  }

  @keyframes animate-svg-fill-1 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(47, 47, 47);
    }
  }

  .logo-animation-1 {
    -webkit-animation: animate-svg-stroke-1 3s ease 0s both,
      animate-svg-fill-1 3s ease 0.8s both;
    animation: animate-svg-stroke-1 3s ease 0s both,
      animate-svg-fill-1 3s ease 0.8s both;
  }

  @-webkit-keyframes animate-svg-stroke-2 {
    0% {
      stroke-dashoffset: 1951.572021484375px;
      stroke-dasharray: 1951.572021484375px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 1951.572021484375px;
    }
  }

  @keyframes animate-svg-stroke-2 {
    0% {
      stroke-dashoffset: 1951.572021484375px;
      stroke-dasharray: 1951.572021484375px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 1951.572021484375px;
    }
  }

  @-webkit-keyframes animate-svg-fill-2 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(47, 47, 47);
    }
  }

  @keyframes animate-svg-fill-2 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(47, 47, 47);
    }
  }

  .logo-animation-2 {
    -webkit-animation: animate-svg-stroke-2 3s ease 0.12s both,
      animate-svg-fill-2 3s ease 0.9s both;
    animation: animate-svg-stroke-2 3s ease 0.12s both,
      animate-svg-fill-2 3s ease 0.9s both;
  }
`;
